/**
 * Regenerates `src/ui/fonts.css` — the self-hosted webfonts.
 *
 * The handoff calls for Space Grotesk (400, 500) and IBM Plex Mono (400, 500),
 * self-hosted in production. HA dashboards routinely run on LAN-only tablets, so
 * the font files are embedded as data URIs: no second request, no CDN, and the
 * single-file panel bundle stays single-file.
 *
 * Only the `latin` subset is kept — that is what the UI's Dutch copy needs.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500&family=IBM+Plex+Mono:wght@400;500&display=swap';

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

/** Splits the stylesheet into `/* subset *\/ @font-face { … }` pairs. */
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];

const out = [
  '/*',
  ' * Self-hosted webfonts, generated by scripts/fetch-fonts.mjs — do not edit.',
  ' * Space Grotesk and IBM Plex Mono are both SIL Open Font License 1.1.',
  ' *',
  ' * These rules are injected into the document head, not the shadow root:',
  ' * @font-face is ignored inside a shadow root.',
  ' */',
  '',
];

let kept = 0;
for (const [, subset, block] of blocks) {
  if (subset !== 'latin') continue;
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  const buffer = Buffer.from(await (await fetch(url)).arrayBuffer());
  const dataUri = `data:font/woff2;base64,${buffer.toString('base64')}`;
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  console.log(`${family} ${weight} — ${(buffer.length / 1024).toFixed(1)} kB`);

  out.push(
    block
      .replace(/url\(https:[^)]+\.woff2\)/, `url(${dataUri})`)
      .replace(/\s*unicode-range:[^;]+;/, '')
      .replace(/\n\s*/g, '\n  ')
      .trim(),
    '',
  );
  kept += 1;
}

if (kept === 0) throw new Error('no latin @font-face blocks found — did the CSS format change?');

await writeFile(new URL('../src/ui/fonts.css', import.meta.url), out.join('\n'));
console.log(`wrote src/ui/fonts.css (${kept} faces)`);
